name: Run tests
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        account_type:
          - personal
          - business
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install \
            gcc \
            pkg-config \
            libwebkit2gtk-4.0-dev \
            libjson-glib-dev \
            dbus \
            dbus-x11 \
            make \
            wget \
            rpm \
            awscli \
            libreoffice \
            gdb \
            systemd-coredump
          sudo rm /usr/local/bin/aws  # whyyy

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Check go formatting
        run: |
          go get golang.org/x/tools/cmd/goimports
          [ -z "$(goimports -l .)" ]

      - name: Check that the app compiles successfully
        run: make
        env:
          CFLAGS: -g

      - name: Copy auth tokens from S3
        run: |
          which aws
          aws --version
          aws s3 cp s3://fusefs-travis/$ACCOUNT_TYPE/.auth_tokens.json .
          aws s3 cp s3://fusefs-travis/dmel.fa.gz .
          gunzip dmel.fa.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCOUNT_TYPE: ${{ matrix.account_type }}

      - name: Run c tests
        run: |
          sudo cp resources/onedriver@.service /etc/systemd/user
          sudo cp onedriver /usr/bin
          export XDG_RUNTIME_DIR="/run/user/$(id -u)"
          export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
          sudo mkdir -p -m 0700 $XDG_RUNTIME_DIR
          sudo chown $(whoami). $XDG_RUNTIME_DIR
          sudo systemctl start user@$(id -u).service
          make build/c-test
          if ! dbus-launch build/c-test ; then
            sleep 5
            coredumpctl dump > c-test.core
            printf 'bt\nq\n' > backtrace.gdb
            gdb -batch -x backtrace.gdb build/c-test c-test.core
          fi
        env:
          CFLAGS: -g
        continue-on-error: true

      - name: Run tests
        run: |
          go get -u github.com/rakyll/gotest 
          gotest -v -covermode=count -coverpkg=./fs/... -coverprofile=graph.coverage ./fs/graph
          gotest -v -covermode=count -coverpkg=./fs/... -coverprofile=fs.coverage ./fs
          go test -c -covermode=count -coverpkg=./fs/... ./fs/offline
          sudo unshare -n -S $(id -u) -G $(id -g) ./offline.test -test.v -test.coverprofile=offline.coverage

      - name: Copy new auth tokens to S3
        run: /usr/bin/aws s3 cp .auth_tokens.json s3://fusefs-travis/$ACCOUNT_TYPE/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCOUNT_TYPE: ${{ matrix.account_type }}
        if: always()

      - name: Combine test coverage into single file
        run: |
          go get github.com/wadey/gocovmerge
          gocovmerge *.coverage > coverage.out

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.5
          
      - name: Send test coverage to Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          flag-name: ${{ matrix.account_type }}
          parallel: true
  finish:
    name: Complete Coveralls run
    needs: test
    if: always()
    runs-on: ubuntu-20.04
    steps:
    - name: Coveralls finished
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
